### ISSUE TITLE
Breaking changes between versions 1.0.0 and 1.1.5

### ISSUE THREAD

**Issue by NMe84** [cardgate/cardgate-clientlib-php#2]
So between versions 1.0.0 and 1.1.5 apparently you decided to change the name of a method in `Transaction` from `getCustomer` to `getConsumer`.

1. Breaking changes like that [belong](https://semver.org/) in a new major version, not in a minor. You advise people to use "~1.1.4" (used to be "~1.0.0") in your installation instructions but simply updating dependencies will break people's code like it just did for me on a live website. Composer and semver are supposed to prevent that sort of thing.
2. If you do want to make a change like this, keep the old function with a `@deprecated` annotation stating **exactly** in which version the function will be removed. Have it internally call the new function until it is actually removed.

If you're going to supply people with an SDK you'll have to maintain some stability. This is not a way to build trust with developers.

**Comment by cardgate** [comment]
Thank you for reporting this issue. A patch has been made in the master branch to fix this issue. Can you verify wether or not this solves your problem? If it does, a new release will be created with the patch applied.

**Comment by NMe84** [comment]
Looks like a good fix to me.

**Comment by cardgate** [comment]
Thank you, closing this issue.
